### ISSUE TITLE
Hook  Dialog error，尝试多部手机不能解决，  XposedHelpers.findAndHookMethod（）没问题

### ISSUE THREAD

**Issue by ChaoXiGo** [w296488320/XposedAppium#10]
发现匹配的App
Hook Activity->dispatchActivityResumed error no hook provider setup, and not running xposed environment
Hook  Dialog error  : no hook provider setup, and not running xposed environment
java.lang.IllegalStateException: no hook provider setup, and not running xposed environment
	at com.zhenxi.Superappium.xpcompat.XpCompatEngine.getsHookProvider(XpCompatEngine.java:58)
	at com.zhenxi.Superappium.xpcompat.XpCompatEngine.hookMethod(XpCompatEngine.java:15)
	at com.zhenxi.Superappium.xpcompat.XpCompatEngine.hookAllConstructors(XpCompatEngine.java:20)
	at com.zhenxi.Superappium.PageManager.enablePageMonitor(PageManager.java:410)
	at com.zhenxi.Superappium.PageManager.<clinit>(PageManager.java:43)
	at com.zhenxi.Superappium.PageManager.setTaskDuration(PageManager.java:149)
	at com.example.xposeddemo.LHook.handleLoadPackage(LHook.java:23)
	at FS.JnYy.L.uticzNFpYndx.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at FS.JnYy.L.uticzNFpYndx.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at FS.JnYy.L.uticzNFpYndx.callbacks.XCallback.callAll(Unknown Source:26)
	at g0.a(Unknown Source:281)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:250)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1062)
	at android.app.LoadedApk.getResources(LoadedApk.java:1310)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3040)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3032)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6805)
	at android.app.ActivityThread.access$1500(ActivityThread.java:259)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2094)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8015)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1091)

**Comment by ChaoXiGo** [comment]
以上为错误日志信息

**Comment by ChaoXiGo** [comment]
补充一条， CLogUtils.e("AddHandleActivity 注册完毕 "); 执行了
